### ISSUE TITLE
EX REP 炸了

### ISSUE THREAD

**Issue by williewillus** [Keiwaamung/STG-THBDB-Bug-Report#1]
**详情以及复现方法**
* rep: https://paste.vincent-lee.net/f/5d5ee68fa7ba6a9d
* rep應該是通關的，結果七符沒了
* 好像是有概率的，不一定每一次都炸
  * 如果不炸就重開遊戲再放rep
* 七符之前都符合我記憶中的流程，應該是七符本身出問題

**相关截图**
如果可能，请在出现问题的时候截图并粘贴到下方。
如果遇到游戏弹出报错窗口，请尽量截图下来，方便我们定位问题。

**游戏日志文件（engine.log）**
如果可能，请把游戏的日志文件发送给我们（在游戏存档目录），方便我们定位问题。
播放rep瘡了之後的engine.log: [engine.log](https://github.com/Keiwaamung/THBDB-Bug-Report/files/6525765/engine.log)

**系统信息（请尽量填写完整）：**
 - 操作系统：Linux （Steam Proton）
 - 游戏版本（可在游戏画面右下角找到）：1.0.0

**其他信息**

**Comment by Demonese** [comment]
已在新版本v1.1.0中修复
